"""Initial DB models setup

Revision ID: ec27be7030bb
Revises:
Create Date: 2025-09-20 20:13:41.474043

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ec27be7030bb"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cocktails",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "glassware",
            sa.Enum(
                "MARGARITA",
                "MARTINI",
                "COCKTAIL",
                "HIGHBALL",
                "COLLINS",
                "COUPE",
                "HURRICANE",
                "SHOT",
                "OLD_FASHIONED",
                "SNIFTER",
                "NICK_AND_NORA",
                "IRISH_COFFEE",
                "COPPER_MUG",
                "SOUR",
                "CORDIAL",
                "LOWBALL",
                "WINE",
                "CHAMPAGNE",
                "TIKI",
                "BEER_MUG",
                "PINT",
                "GLENCAIRN",
                "JULEP",
                name="cocktailglassware",
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cocktails_name"), "cocktails", ["name"], unique=True)
    op.create_table(
        "ingredients",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=124), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ingredients_name"), "ingredients", ["name"], unique=True)
    op.create_table(
        "tags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tags_name"), "tags", ["name"], unique=True)
    op.create_table(
        "cocktail_tag_association",
        sa.Column("cocktail_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cocktail_id"],
            ["cocktails.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.id"],
        ),
        sa.PrimaryKeyConstraint("cocktail_id", "tag_id"),
    )
    op.create_table(
        "steps",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "action",
            sa.Enum(
                "ADD_INGREDIENT",
                "MUDDLE",
                "SHAKE",
                "BLEND",
                "STIR",
                "POUR",
                "PEEL",
                "GRATE",
                "DECORATE",
                name="stepaction",
            ),
            nullable=False,
        ),
        sa.Column("ingredient_id", sa.Integer(), nullable=True),
        sa.Column(
            "measuring_unit",
            sa.Enum(
                "ML",
                "OZ",
                "KG",
                "LB",
                "DASH",
                "TSP",
                "TBSP",
                "CUP",
                "PINT",
                "QUART",
                "GALLON",
                "LITER",
                "GRAM",
                "SLICE",
                "WEDGE",
                "PIECE",
                "CUBE",
                "LEAF",
                "PINCH",
                name="measuringunit",
            ),
            nullable=True,
        ),
        sa.Column("quantity", sa.Float(), nullable=True),
        sa.Column(
            "mixology_tool",
            sa.Enum(
                "COCKTAIL_SHAKER",
                "HAWTHORNE_STRAINER",
                "JULEP_STRAINER",
                "FINE_MESH_STRIANER",
                "PEELER",
                "GRATER",
                "BLENDER",
                "MUDDLER",
                "JIGGER",
                "STIRRING_SPOON",
                "STIRRING_JAR",
                name="mixologytool",
            ),
            nullable=True,
        ),
        sa.Column("next_step_id", sa.Integer(), nullable=True),
        sa.Column("is_recipe_first_step", sa.Boolean(), nullable=False),
        sa.Column("cocktail_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["cocktail_id"], ["cocktails.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["ingredient_id"],
            ["ingredients.id"],
        ),
        sa.ForeignKeyConstraint(["next_step_id"], ["steps.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("steps")
    op.drop_table("cocktail_tag_association")
    op.drop_index(op.f("ix_tags_name"), table_name="tags")
    op.drop_table("tags")
    op.drop_index(op.f("ix_ingredients_name"), table_name="ingredients")
    op.drop_table("ingredients")
    op.drop_index(op.f("ix_cocktails_name"), table_name="cocktails")
    op.drop_table("cocktails")
    # ### end Alembic commands ###
